CREATE TABLE EVENTTYPE(
ID BIGINT NOT NULL PRIMARY KEY,
EVENTTYPE VARCHAR(2500) NOT NULL,
PERSONAL_MESSAGE_ID BIGINT,
CREATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT EVENT_MSG_FK FOREIGN KEY (PERSONAL_MESSAGE_ID) REFERENCES PERSONALMESSAGE(ID)
);

CREATE SEQUENCE IF NOT EXISTS EVENTTYPE_SEQ
START WITH 100000
INCREMENT BY 1;