CREATE TABLE PERSONALMESSAGE(
ID BIGINT NOT NULL PRIMARY KEY,
MESSAGE VARCHAR(2500),
CREATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS PERSONALMSG_SEQ
START WITH 100000
INCREMENT BY 1;

