 CREATE TABLE USER(
 ID BIGINT NOT NULL PRIMARY KEY,
 FROMADDRESS VARCHAR(150) NOT NULL,
 TOADDRESS VARCHAR(150) NOT NULL,
 USERNAME VARCHAR(100) NOT NULL,
 SENDERNAME VARCHAR(100) NOT NULL,
 REMAINDER BOOLEAN NOT NULL,
 WISHED BOOLEAN NOT NULL,
 CREATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 EVENTDATE TIMESTAMP NOT NULL,
 EVENT_ID BIGINT NOT NULL,
 CONSTRAINT USER_EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENTTYPE(ID),
 CONSTRAINT USER_EVENT_UQ UNIQUE(EVENT_ID)
 );

 CREATE SEQUENCE IF NOT EXISTS USER_SEQ
 START WITH 100000
 INCREMENT BY 1;